// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Ollie control-plane↔agent gRPC service (v1alpha1). See
// docs/design/control-plane.md §4 and ADR-0022 for the design and
// the v0.4 scope cuts (identity messages reserved but not used).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: controlplane/v1/controlplane.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonitoringSpecDelta_Op int32

const (
	MonitoringSpecDelta_OP_UNSPECIFIED MonitoringSpecDelta_Op = 0
	MonitoringSpecDelta_UPSERT         MonitoringSpecDelta_Op = 1
	MonitoringSpecDelta_REMOVE         MonitoringSpecDelta_Op = 2
)

// Enum value maps for MonitoringSpecDelta_Op.
var (
	MonitoringSpecDelta_Op_name = map[int32]string{
		0: "OP_UNSPECIFIED",
		1: "UPSERT",
		2: "REMOVE",
	}
	MonitoringSpecDelta_Op_value = map[string]int32{
		"OP_UNSPECIFIED": 0,
		"UPSERT":         1,
		"REMOVE":         2,
	}
)

func (x MonitoringSpecDelta_Op) Enum() *MonitoringSpecDelta_Op {
	p := new(MonitoringSpecDelta_Op)
	*p = x
	return p
}

func (x MonitoringSpecDelta_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MonitoringSpecDelta_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_v1_controlplane_proto_enumTypes[0].Descriptor()
}

func (MonitoringSpecDelta_Op) Type() protoreflect.EnumType {
	return &file_controlplane_v1_controlplane_proto_enumTypes[0]
}

func (x MonitoringSpecDelta_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MonitoringSpecDelta_Op.Descriptor instead.
func (MonitoringSpecDelta_Op) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{8, 0}
}

// AgentMessage is anything the agent sends up the stream.
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Status
	//	*AgentMessage_Digest
	Body          isAgentMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetBody() isAgentMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentMessage) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *AgentHeartbeat {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetStatus() *AgentStatus {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *AgentMessage) GetDigest() *AgentLocalDigest {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Digest); ok {
			return x.Digest
		}
	}
	return nil
}

type isAgentMessage_Body interface {
	isAgentMessage_Body()
}

type AgentMessage_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *AgentHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Status struct {
	Status *AgentStatus `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type AgentMessage_Digest struct {
	Digest *AgentLocalDigest `protobuf:"bytes,4,opt,name=digest,proto3,oneof"` // for resync detection on reconnect
}

func (*AgentMessage_Hello) isAgentMessage_Body() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Body() {}

func (*AgentMessage_Status) isAgentMessage_Body() {}

func (*AgentMessage_Digest) isAgentMessage_Body() {}

// ControllerMessage is anything the controller sends down the stream.
// Tags 3 (identity_snapshot), 4 (identity_delta), 5 (sink_rotation)
// are reserved for forward compatibility — no payload in v0.4 per
// ADR-0022.5.
type ControllerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ControllerMessage_Hello
	//	*ControllerMessage_SpecDelta
	//	*ControllerMessage_Heartbeat
	Body          isControllerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *ControllerMessage) GetBody() isControllerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ControllerMessage) GetHello() *ControllerHello {
	if x != nil {
		if x, ok := x.Body.(*ControllerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ControllerMessage) GetSpecDelta() *MonitoringSpecDelta {
	if x != nil {
		if x, ok := x.Body.(*ControllerMessage_SpecDelta); ok {
			return x.SpecDelta
		}
	}
	return nil
}

func (x *ControllerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*ControllerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isControllerMessage_Body interface {
	isControllerMessage_Body()
}

type ControllerMessage_Hello struct {
	Hello *ControllerHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ControllerMessage_SpecDelta struct {
	SpecDelta *MonitoringSpecDelta `protobuf:"bytes,2,opt,name=spec_delta,json=specDelta,proto3,oneof"`
}

type ControllerMessage_Heartbeat struct {
	// 3 = identity_snapshot (reserved, see ADR-0022.5)
	// 4 = identity_delta (reserved, see ADR-0022.5)
	// 5 = sink_rotation (reserved)
	Heartbeat *Heartbeat `protobuf:"bytes,6,opt,name=heartbeat,proto3,oneof"`
}

func (*ControllerMessage_Hello) isControllerMessage_Body() {}

func (*ControllerMessage_SpecDelta) isControllerMessage_Body() {}

func (*ControllerMessage_Heartbeat) isControllerMessage_Body() {}

// AgentHello opens the session.
type AgentHello struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	NodeName     string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AgentVersion string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// SupportedModules lists capture.Module names the agent's OBI
	// build supports — controller filters MonitoringSpec deltas to
	// modules the agent can actually do.
	SupportedModules []string `protobuf:"bytes,3,rep,name=supported_modules,json=supportedModules,proto3" json:"supported_modules,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *AgentHello) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AgentHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHello) GetSupportedModules() []string {
	if x != nil {
		return x.SupportedModules
	}
	return nil
}

// ControllerHello acknowledges the session.
type ControllerHello struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ControllerVersion string                 `protobuf:"bytes,1,opt,name=controller_version,json=controllerVersion,proto3" json:"controller_version,omitempty"`
	// MinAgentVersion is the minimum agent version this controller will
	// serve. Agent must disconnect and not retry if its version is
	// below this — agent operator needs to upgrade.
	MinAgentVersion string `protobuf:"bytes,2,opt,name=min_agent_version,json=minAgentVersion,proto3" json:"min_agent_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ControllerHello) Reset() {
	*x = ControllerHello{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerHello) ProtoMessage() {}

func (x *ControllerHello) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerHello.ProtoReflect.Descriptor instead.
func (*ControllerHello) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *ControllerHello) GetControllerVersion() string {
	if x != nil {
		return x.ControllerVersion
	}
	return ""
}

func (x *ControllerHello) GetMinAgentVersion() string {
	if x != nil {
		return x.MinAgentVersion
	}
	return ""
}

// AgentHeartbeat fires every ~5s while the stream is up.
type AgentHeartbeat struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Ts                  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	ActiveMonitorCount  uint32                 `protobuf:"varint,2,opt,name=active_monitor_count,json=activeMonitorCount,proto3" json:"active_monitor_count,omitempty"`
	ModuleEventCounts   map[string]uint64      `protobuf:"bytes,3,rep,name=module_event_counts,json=moduleEventCounts,proto3" json:"module_event_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	LastKnownGeneration int64                  `protobuf:"varint,4,opt,name=last_known_generation,json=lastKnownGeneration,proto3" json:"last_known_generation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentHeartbeat) Reset() {
	*x = AgentHeartbeat{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeat) ProtoMessage() {}

func (x *AgentHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeat.ProtoReflect.Descriptor instead.
func (*AgentHeartbeat) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *AgentHeartbeat) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *AgentHeartbeat) GetActiveMonitorCount() uint32 {
	if x != nil {
		return x.ActiveMonitorCount
	}
	return 0
}

func (x *AgentHeartbeat) GetModuleEventCounts() map[string]uint64 {
	if x != nil {
		return x.ModuleEventCounts
	}
	return nil
}

func (x *AgentHeartbeat) GetLastKnownGeneration() int64 {
	if x != nil {
		return x.LastKnownGeneration
	}
	return 0
}

// Heartbeat from controller back to agent. Same shape both
// directions (just an ack); separate message type lets us add
// directional fields later without a breaking change.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

// AgentStatus reports per-pod monitoring health back so the
// controller can populate CR status. Sent on per-pod state changes
// (apply success, apply failure, pod going away).
type AgentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodUid        string                 `protobuf:"bytes,1,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	ActivePids    uint32                 `protobuf:"varint,3,opt,name=active_pids,json=activePids,proto3" json:"active_pids,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *AgentStatus) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *AgentStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *AgentStatus) GetActivePids() uint32 {
	if x != nil {
		return x.ActivePids
	}
	return 0
}

func (x *AgentStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AgentLocalDigest is sent on reconnect so the controller can diff
// against current state and send only the necessary deltas.
type AgentLocalDigest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of pod_uid → generation the agent currently has applied.
	PodGenerations map[string]int64 `protobuf:"bytes,1,rep,name=pod_generations,json=podGenerations,proto3" json:"pod_generations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentLocalDigest) Reset() {
	*x = AgentLocalDigest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentLocalDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentLocalDigest) ProtoMessage() {}

func (x *AgentLocalDigest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentLocalDigest.ProtoReflect.Descriptor instead.
func (*AgentLocalDigest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *AgentLocalDigest) GetPodGenerations() map[string]int64 {
	if x != nil {
		return x.PodGenerations
	}
	return nil
}

// MonitoringSpecDelta is one apply-or-remove operation against the
// agent's local pod_uid → MonitoringSpec map.
type MonitoringSpecDelta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Op    MonitoringSpecDelta_Op `protobuf:"varint,1,opt,name=op,proto3,enum=ollie.controlplane.v1.MonitoringSpecDelta_Op" json:"op,omitempty"`
	Spec  *MonitoringSpec        `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// Generation is monotonic per pod_uid; agent ignores deltas with
	// generation <= last seen.
	Generation    int64 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringSpecDelta) Reset() {
	*x = MonitoringSpecDelta{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringSpecDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringSpecDelta) ProtoMessage() {}

func (x *MonitoringSpecDelta) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringSpecDelta.ProtoReflect.Descriptor instead.
func (*MonitoringSpecDelta) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *MonitoringSpecDelta) GetOp() MonitoringSpecDelta_Op {
	if x != nil {
		return x.Op
	}
	return MonitoringSpecDelta_OP_UNSPECIFIED
}

func (x *MonitoringSpecDelta) GetSpec() *MonitoringSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *MonitoringSpecDelta) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// MonitoringSpec is the per-pod "what to capture" record. v0.4
// fields map 1:1 onto obiconfig.Instrument on the agent side; see
// docs/design/control-plane.md §2.3.
type MonitoringSpec struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PodUid    string                 `protobuf:"bytes,1,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	PodName   string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	NodeName  string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// PIDHints is the controller's best knowledge of which PIDs this
	// pod's containers map to. Empty means agent resolves locally
	// via cgroup / container-id lookup.
	PidHints []uint32 `protobuf:"varint,5,rep,packed,name=pid_hints,json=pidHints,proto3" json:"pid_hints,omitempty"`
	// Protocols is a bitset (high bit reserved). Module values match
	// capture.Module in the agent.
	Protocols uint32 `protobuf:"varint,6,opt,name=protocols,proto3" json:"protocols,omitempty"`
	// HTTPPorts and similar — used to populate the OBI
	// discovery.instrument open_ports selector.
	HttpPorts []uint32 `protobuf:"varint,7,rep,packed,name=http_ports,json=httpPorts,proto3" json:"http_ports,omitempty"`
	// SourceRef is "TrafficMonitor namespace/name" or
	// "ClusterTrafficPolicy name" — agent doesn't act on it but it
	// helps debugging.
	SourceRef     string `protobuf:"bytes,8,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringSpec) Reset() {
	*x = MonitoringSpec{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringSpec) ProtoMessage() {}

func (x *MonitoringSpec) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringSpec.ProtoReflect.Descriptor instead.
func (*MonitoringSpec) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *MonitoringSpec) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *MonitoringSpec) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *MonitoringSpec) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MonitoringSpec) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *MonitoringSpec) GetPidHints() []uint32 {
	if x != nil {
		return x.PidHints
	}
	return nil
}

func (x *MonitoringSpec) GetProtocols() uint32 {
	if x != nil {
		return x.Protocols
	}
	return 0
}

func (x *MonitoringSpec) GetHttpPorts() []uint32 {
	if x != nil {
		return x.HttpPorts
	}
	return nil
}

func (x *MonitoringSpec) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

var File_controlplane_v1_controlplane_proto protoreflect.FileDescriptor

const file_controlplane_v1_controlplane_proto_rawDesc = "" +
	"\n" +
	"\"controlplane/v1/controlplane.proto\x12\x15ollie.controlplane.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x02\n" +
	"\fAgentMessage\x129\n" +
	"\x05hello\x18\x01 \x01(\v2!.ollie.controlplane.v1.AgentHelloH\x00R\x05hello\x12E\n" +
	"\theartbeat\x18\x02 \x01(\v2%.ollie.controlplane.v1.AgentHeartbeatH\x00R\theartbeat\x12<\n" +
	"\x06status\x18\x03 \x01(\v2\".ollie.controlplane.v1.AgentStatusH\x00R\x06status\x12A\n" +
	"\x06digest\x18\x04 \x01(\v2'.ollie.controlplane.v1.AgentLocalDigestH\x00R\x06digestB\x06\n" +
	"\x04body\"\xea\x01\n" +
	"\x11ControllerMessage\x12>\n" +
	"\x05hello\x18\x01 \x01(\v2&.ollie.controlplane.v1.ControllerHelloH\x00R\x05hello\x12K\n" +
	"\n" +
	"spec_delta\x18\x02 \x01(\v2*.ollie.controlplane.v1.MonitoringSpecDeltaH\x00R\tspecDelta\x12@\n" +
	"\theartbeat\x18\x06 \x01(\v2 .ollie.controlplane.v1.HeartbeatH\x00R\theartbeatB\x06\n" +
	"\x04body\"{\n" +
	"\n" +
	"AgentHello\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12+\n" +
	"\x11supported_modules\x18\x03 \x03(\tR\x10supportedModules\"l\n" +
	"\x0fControllerHello\x12-\n" +
	"\x12controller_version\x18\x01 \x01(\tR\x11controllerVersion\x12*\n" +
	"\x11min_agent_version\x18\x02 \x01(\tR\x0fminAgentVersion\"\xd6\x02\n" +
	"\x0eAgentHeartbeat\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x120\n" +
	"\x14active_monitor_count\x18\x02 \x01(\rR\x12activeMonitorCount\x12l\n" +
	"\x13module_event_counts\x18\x03 \x03(\v2<.ollie.controlplane.v1.AgentHeartbeat.ModuleEventCountsEntryR\x11moduleEventCounts\x122\n" +
	"\x15last_known_generation\x18\x04 \x01(\x03R\x13lastKnownGeneration\x1aD\n" +
	"\x16ModuleEventCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"7\n" +
	"\tHeartbeat\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\"u\n" +
	"\vAgentStatus\x12\x17\n" +
	"\apod_uid\x18\x01 \x01(\tR\x06podUid\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x1f\n" +
	"\vactive_pids\x18\x03 \x01(\rR\n" +
	"activePids\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xbb\x01\n" +
	"\x10AgentLocalDigest\x12d\n" +
	"\x0fpod_generations\x18\x01 \x03(\v2;.ollie.controlplane.v1.AgentLocalDigest.PodGenerationsEntryR\x0epodGenerations\x1aA\n" +
	"\x13PodGenerationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xe1\x01\n" +
	"\x13MonitoringSpecDelta\x12=\n" +
	"\x02op\x18\x01 \x01(\x0e2-.ollie.controlplane.v1.MonitoringSpecDelta.OpR\x02op\x129\n" +
	"\x04spec\x18\x02 \x01(\v2%.ollie.controlplane.v1.MonitoringSpecR\x04spec\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x03R\n" +
	"generation\"0\n" +
	"\x02Op\x12\x12\n" +
	"\x0eOP_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06UPSERT\x10\x01\x12\n" +
	"\n" +
	"\x06REMOVE\x10\x02\"\xf8\x01\n" +
	"\x0eMonitoringSpec\x12\x17\n" +
	"\apod_uid\x18\x01 \x01(\tR\x06podUid\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12\x1b\n" +
	"\tpid_hints\x18\x05 \x03(\rR\bpidHints\x12\x1c\n" +
	"\tprotocols\x18\x06 \x01(\rR\tprotocols\x12\x1d\n" +
	"\n" +
	"http_ports\x18\a \x03(\rR\thttpPorts\x12\x1d\n" +
	"\n" +
	"source_ref\x18\b \x01(\tR\tsourceRef2q\n" +
	"\fControlPlane\x12a\n" +
	"\fAgentSession\x12#.ollie.controlplane.v1.AgentMessage\x1a(.ollie.controlplane.v1.ControllerMessage(\x010\x01B@Z>github.com/gke-labs/in-cluster-observability/pkg/controller/pbb\x06proto3"

var (
	file_controlplane_v1_controlplane_proto_rawDescOnce sync.Once
	file_controlplane_v1_controlplane_proto_rawDescData []byte
)

func file_controlplane_v1_controlplane_proto_rawDescGZIP() []byte {
	file_controlplane_v1_controlplane_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_controlplane_proto_rawDesc), len(file_controlplane_v1_controlplane_proto_rawDesc)))
	})
	return file_controlplane_v1_controlplane_proto_rawDescData
}

var file_controlplane_v1_controlplane_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controlplane_v1_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_controlplane_v1_controlplane_proto_goTypes = []any{
	(MonitoringSpecDelta_Op)(0),   // 0: ollie.controlplane.v1.MonitoringSpecDelta.Op
	(*AgentMessage)(nil),          // 1: ollie.controlplane.v1.AgentMessage
	(*ControllerMessage)(nil),     // 2: ollie.controlplane.v1.ControllerMessage
	(*AgentHello)(nil),            // 3: ollie.controlplane.v1.AgentHello
	(*ControllerHello)(nil),       // 4: ollie.controlplane.v1.ControllerHello
	(*AgentHeartbeat)(nil),        // 5: ollie.controlplane.v1.AgentHeartbeat
	(*Heartbeat)(nil),             // 6: ollie.controlplane.v1.Heartbeat
	(*AgentStatus)(nil),           // 7: ollie.controlplane.v1.AgentStatus
	(*AgentLocalDigest)(nil),      // 8: ollie.controlplane.v1.AgentLocalDigest
	(*MonitoringSpecDelta)(nil),   // 9: ollie.controlplane.v1.MonitoringSpecDelta
	(*MonitoringSpec)(nil),        // 10: ollie.controlplane.v1.MonitoringSpec
	nil,                           // 11: ollie.controlplane.v1.AgentHeartbeat.ModuleEventCountsEntry
	nil,                           // 12: ollie.controlplane.v1.AgentLocalDigest.PodGenerationsEntry
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_controlplane_v1_controlplane_proto_depIdxs = []int32{
	3,  // 0: ollie.controlplane.v1.AgentMessage.hello:type_name -> ollie.controlplane.v1.AgentHello
	5,  // 1: ollie.controlplane.v1.AgentMessage.heartbeat:type_name -> ollie.controlplane.v1.AgentHeartbeat
	7,  // 2: ollie.controlplane.v1.AgentMessage.status:type_name -> ollie.controlplane.v1.AgentStatus
	8,  // 3: ollie.controlplane.v1.AgentMessage.digest:type_name -> ollie.controlplane.v1.AgentLocalDigest
	4,  // 4: ollie.controlplane.v1.ControllerMessage.hello:type_name -> ollie.controlplane.v1.ControllerHello
	9,  // 5: ollie.controlplane.v1.ControllerMessage.spec_delta:type_name -> ollie.controlplane.v1.MonitoringSpecDelta
	6,  // 6: ollie.controlplane.v1.ControllerMessage.heartbeat:type_name -> ollie.controlplane.v1.Heartbeat
	13, // 7: ollie.controlplane.v1.AgentHeartbeat.ts:type_name -> google.protobuf.Timestamp
	11, // 8: ollie.controlplane.v1.AgentHeartbeat.module_event_counts:type_name -> ollie.controlplane.v1.AgentHeartbeat.ModuleEventCountsEntry
	13, // 9: ollie.controlplane.v1.Heartbeat.ts:type_name -> google.protobuf.Timestamp
	12, // 10: ollie.controlplane.v1.AgentLocalDigest.pod_generations:type_name -> ollie.controlplane.v1.AgentLocalDigest.PodGenerationsEntry
	0,  // 11: ollie.controlplane.v1.MonitoringSpecDelta.op:type_name -> ollie.controlplane.v1.MonitoringSpecDelta.Op
	10, // 12: ollie.controlplane.v1.MonitoringSpecDelta.spec:type_name -> ollie.controlplane.v1.MonitoringSpec
	1,  // 13: ollie.controlplane.v1.ControlPlane.AgentSession:input_type -> ollie.controlplane.v1.AgentMessage
	2,  // 14: ollie.controlplane.v1.ControlPlane.AgentSession:output_type -> ollie.controlplane.v1.ControllerMessage
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_controlplane_v1_controlplane_proto_init() }
func file_controlplane_v1_controlplane_proto_init() {
	if File_controlplane_v1_controlplane_proto != nil {
		return
	}
	file_controlplane_v1_controlplane_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Status)(nil),
		(*AgentMessage_Digest)(nil),
	}
	file_controlplane_v1_controlplane_proto_msgTypes[1].OneofWrappers = []any{
		(*ControllerMessage_Hello)(nil),
		(*ControllerMessage_SpecDelta)(nil),
		(*ControllerMessage_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_controlplane_proto_rawDesc), len(file_controlplane_v1_controlplane_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_v1_controlplane_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_controlplane_proto_depIdxs,
		EnumInfos:         file_controlplane_v1_controlplane_proto_enumTypes,
		MessageInfos:      file_controlplane_v1_controlplane_proto_msgTypes,
	}.Build()
	File_controlplane_v1_controlplane_proto = out.File
	file_controlplane_v1_controlplane_proto_goTypes = nil
	file_controlplane_v1_controlplane_proto_depIdxs = nil
}
